language: csharp
mono: none
dotnet: 2.2.100
sudo: required
dist: xenial
script:
- dotnet restore
- dotnet test
before_install:
- openssl aes-256-cbc -K $encrypted_d9a44da3c1b2_key -iv $encrypted_d9a44da3c1b2_iv
  -in autenticatedLadderDeploy.enc -out autenticatedLadderDeploy -d
