// <auto-generated />
using System;
using AuthenticatedLadder.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticatedLadder.Migrations
{
    [DbContext(typeof(LadderDBContext))]
    [Migration("20190209154334_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("AuthenticatedLadder.DomainModels.LadderEntry", b =>
                {
                    b.Property<string>("LadderId");

                    b.Property<string>("Platform");

                    b.Property<string>("Username");

                    b.Property<DateTime>("EntryDate");

                    b.Property<long>("Score");

                    b.HasKey("LadderId", "Platform", "Username");

                    b.ToTable("Ladders");
                });
#pragma warning restore 612, 618
        }
    }
}
